// Database row types, derived from the generated schema rather than hand-written,
// plus the two boundaries where a derived type is not enough on its own.
//
// These types used to be five hand-written interfaces in `api.ts`, and every
// query ended with `return data as Party` — an unchecked cast asserting that the
// database matches the interface. It does not have to. Twice the assertion was
// wrong and nothing caught it:
//
//   - `get_party_by_code` did not return `max_votes` while `Party` declared
//     `max_votes: number`, so a host who picked 7 votes silently got 5
//     (fixed in 20260901172918; the cast is why it survived a full CI cycle).
//   - `Situation.emoji` was declared `string` against a column that is
//     genuinely NULL for pool-sourced rows. The column has since been dropped
//     (20260907170000) rather than repaired, because nothing rendered it.
//
// Both are the same failure: a hand-written type asserting a shape, an `as`
// laundering the difference, and no layer left that could disagree. Enabling
// `strict` did not fix it and could not — a cast outranks every compiler flag.
//
// So the interfaces are gone. `Row<"parties">` is generated by
// `supabase gen types` from the real schema, which makes the schema the single
// source of truth and a drifted column a build error instead of `undefined` at
// runtime.
//
// This module deliberately imports nothing but the generated types and zod: it
// stays free of the Supabase client, which touches `localStorage` at module
// scope and cannot be imported in a Node test environment (same reason
// `resultsRules.ts` exists). That is what makes the boundaries below testable.

import { z } from "zod";
import type { Database } from "@/integrations/supabase/types";

type Row<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];

// ─── Row types ───────────────────────────────────────────────────────────────

export type Participant = Row<"participants">;
export type Situation = Row<"situations">;
export type Photo = Row<"photos">;
export type Vote = Row<"votes">;

/**
 * `parties.status` is `TEXT` constrained by
 * `CHECK (status IN ('waiting', 'playing', 'ended'))`
 * (20260627030404_tables_and_rls.sql). `supabase gen types` widens a CHECK to
 * `string`, so the generated Row loses a guarantee the database really makes.
 *
 * Narrowing it back is faithful to the constraint — but it is still a claim
 * about data, so it is *checked* at the boundary (`toParty`) rather than
 * asserted with a cast. That is the whole difference between this and the code
 * it replaces.
 *
 * `'ended'` is in the constraint and no application code writes it. It is
 * listed because the database permits it, not because a path produces it.
 */
export const PARTY_STATUSES = ["waiting", "playing", "ended"] as const;
export type PartyStatus = (typeof PARTY_STATUSES)[number];

export function isPartyStatus(value: string): value is PartyStatus {
  // `.some` rather than `PARTY_STATUSES.includes(value)`: the tuple is
  // `readonly ["waiting", ...]`, so `includes` rejects a plain `string`
  // argument, and the usual workaround is the assertion this file bans.
  return PARTY_STATUSES.some((status) => status === value);
}

/**
 * Flattened rather than left as `Omit<…> & { status }`. An intersection and the
 * flat object type it describes are structurally identical but not *identical*,
 * and the invariant `Equal` assertions below compare identity — so the
 * intersection form silently failed the check it was written to pass. It also
 * reads better on hover: one list of columns instead of `A & B`.
 */
type Flatten<T> = { [K in keyof T]: T[K] };

export type Party = Flatten<
  Omit<Row<"parties">, "status"> & { status: PartyStatus }
>;

/** A `parties` row as the client receives it, before `status` is narrowed. */
type PartyRowLike = Omit<Row<"parties">, "status"> & { status: string };

/**
 * The one place a `parties` row becomes a `Party`. Throws rather than casting:
 * a status outside the CHECK constraint means the schema moved and the code did
 * not, which is worth a loud failure and not a silent widening.
 */
export function toParty(row: PartyRowLike): Party {
  if (!isPartyStatus(row.status)) {
    throw new Error(
      `Unknown party status "${row.status}" — expected one of ${PARTY_STATUSES.join(", ")}`
    );
  }
  return { ...row, status: row.status };
}

// ─── The jsonb boundary ──────────────────────────────────────────────────────

/**
 * `create_party_with_host` returns `jsonb`, which the generated types can only
 * describe as `Json`. No amount of deriving helps here — Postgres hands back an
 * opaque blob — so this is the one boundary that needs a *runtime* check, and
 * `api.ts` previously used the worst cast in the file for it:
 * `data as unknown as { party: Party; participant: Participant }`.
 *
 * The schemas below are hand-written, which is exactly what this change set is
 * removing everywhere else. They are welded back to the generated types so that
 * drift breaks the build: hand-written shape, generated source of truth.
 *
 * The weld takes two parts, and it needs both.
 *
 * `satisfies ZodShapeFor<T>` checks the *keys*: a column added to the type
 * makes the shape incomplete, a removed one makes it an excess property, and a
 * plainly retyped one (`z.string()` for a `number`) fails on the value.
 *
 * That is not enough on its own, and the gap is the exact one this module
 * exists for. `z.ZodType` is covariant in its output, so `z.string()` still
 * satisfies `z.ZodType<string | null>` — a column *widened to nullable* would
 * pass the shape check and then throw at runtime on the first NULL. That is the
 * `situations.emoji` drift class, reproduced inside its own guard. So each
 * schema also carries an `Equal<z.infer<…>, T>` assertion, which is invariant
 * and catches it.
 *
 * Note that `satisfies` is load-bearing rather than stylistic: annotating the
 * const (`const shape: ZodShapeFor<T> = …`) erases the literal type, and
 * `z.infer` then reports the annotation back instead of the real schema —
 * making the assertion pass unconditionally. Verified by breaking each case.
 */
type ZodShapeFor<T> = {
  // The third parameter is the schema's *input*, left as `unknown` on purpose:
  // `pgNumeric` accepts a numeric string and outputs a number, and pinning the
  // input would reject it. Only the output is constrained, which is the half
  // that has to match the database row.
  [K in keyof T]-?: z.ZodType<T[K], z.ZodTypeDef, unknown>;
};

/** Invariant type equality — `extends` alone would accept a widened type. */
type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B
  ? 1
  : 2
  ? true
  : false;
type Assert<T extends true> = T;
const PartyStatusSchema = z.enum(PARTY_STATUSES);

/**
 * `capture_hours` and `voting_hours` are Postgres `numeric`. Over `jsonb` they
 * arrive as JSON numbers — proven, since `parseCreatePartyPayload` has run
 * against the live RPC in CI with a plain `z.number()`. Over the Realtime
 * socket the encoding is a different code path and is not proven from here, and
 * `numeric` is exactly the type drivers most often hand back as a string.
 *
 * Accepting both costs one line and removes the question. The output type is
 * `number` either way, so the `Equal` assertions below still hold and no caller
 * can tell the difference. This is a transport concern, not a laxity: a value
 * that is neither a number nor a numeric string is still rejected.
 */
const pgNumeric = z.union([
  z.number(),
  z.string().regex(/^-?\d+(\.\d+)?$/).transform(Number),
]);

/**
 * The `parties` row contract, shared by the creation RPC, the Realtime socket
 * and `toParty`.
 *
 * It used to be two shapes. `create_party_with_host` built its payload with an
 * explicit `jsonb_build_object` column list (20260627030524_rpc_functions.sql)
 * that omitted `max_votes`, so the creation result was typed
 * `Omit<Party, "max_votes">` — the type stating the hole rather than hiding it
 * behind a cast. `20260907163000` added the column to the RPC, the two shapes
 * converged, and the distinction was deleted rather than kept as decoration: a
 * type that describes a payload the database no longer sends is documentation
 * that has drifted, whatever else it is.
 *
 * **Deriving this from `Party` couples it to the `parties` table on purpose.**
 * Add a column to `parties` and this file stops compiling. That is the
 * `max_votes` incident restated as a build error: a settings column added to
 * the table but not to the RPC that reads it is unreachable by every client,
 * and the failure is otherwise silent.
 *
 * The two-step that follows is the design, not an inconvenience. `tsc` reports
 * a column this shape does not declare; declaring it here then makes
 * `parseCreatePartyPayload` throw unless the RPC sends it too — and Journey 1
 * drives party creation through the UI in the `@smoke` tier, so the omission
 * fails loudly in front of a reviewer rather than silently in front of a user.
 * Both halves are required: the column goes in `jsonb_build_object` *and* here.
 */
const partyShape = {
  id: z.string(),
  code: z.string(),
  name: z.string(),
  host_name: z.string(),
  status: PartyStatusSchema,
  created_at: z.string(),
  ends_at: z.string().nullable(),
  voting_ends_at: z.string().nullable(),
  capture_hours: pgNumeric,
  voting_hours: pgNumeric,
  max_situations: pgNumeric,
  max_votes: pgNumeric,
} satisfies ZodShapeFor<Party>;

const participantShape = {
  id: z.string(),
  party_id: z.string(),
  name: z.string(),
  avatar_emoji: z.string(),
  is_host: z.boolean(),
  joined_at: z.string(),
  user_id: z.string(),
} satisfies ZodShapeFor<Participant>;

const PartySchema = z.object(partyShape);
const ParticipantSchema = z.object(participantShape);

// The invariant half of the weld. Exported only because `noUnusedLocals` would
// otherwise delete the guard as dead code — which it is, at runtime, and that
// is the point: it exists to fail `tsc`.
export type _PartyIsExact = Assert<Equal<z.infer<typeof PartySchema>, Party>>;
export type _ParticipantIsExact = Assert<
  Equal<z.infer<typeof ParticipantSchema>, Participant>
>;

// ─── The realtime boundary ───────────────────────────────────────────────────

/**
 * The third boundary, and the one with the least underneath it.
 *
 * `supabase.channel(...).on("postgres_changes", …)` types `payload.new` as a
 * loose record: there is no generated type for it the way there is for a
 * query. Five handlers used to write `payload.new as Party`, which asserted
 * both the shape *and* the `status` narrowing on a value nobody had checked —
 * and the class has bitten here before: `PartyLobby.tsx` carries a comment
 * about "the previous narrower cast [that] hid the field the vote redirect
 * reads".
 *
 * These return `null` instead of throwing, which is the whole design question
 * and worth stating. A realtime callback has no caller: a throw inside it
 * escapes into the Supabase client and takes down the subscription, so one
 * malformed payload would stop the page reacting to *every* later event.
 * Returning `null` lets the handler drop the single bad event, log it, and stay
 * subscribed. The cost is that a silent drop is invisible, which is why the
 * callers log — and why the skip path has its own unit test rather than being
 * assumed to work.
 */
export function partyFromRealtime(row: unknown): Party | null {
  const parsed = PartySchema.safeParse(row);
  return parsed.success ? parsed.data : null;
}

export function participantFromRealtime(row: unknown): Participant | null {
  const parsed = ParticipantSchema.safeParse(row);
  return parsed.success ? parsed.data : null;
}

export const CreatePartyPayloadSchema = z.object({
  party: PartySchema,
  participant: ParticipantSchema,
});

export type CreatePartyPayload = z.infer<typeof CreatePartyPayloadSchema>;

/**
 * Validates the `create_party_with_host` payload. A missing or retyped column
 * throws here, at the call, instead of surfacing as `undefined` several screens
 * later — which is how the `max_votes` bug reached production.
 */
export function parseCreatePartyPayload(data: unknown): CreatePartyPayload {
  return CreatePartyPayloadSchema.parse(data);
}
